### PR TITLE
Adding CODE_OF_CONDUCT.adoc (draft version)

### PR DESCRIPTION
**Pull request by manmorjim**
Adding the draft version of the Code of Conduct in AsciiDoc format. **The contact email is pending**.

### CODE REVIEW

**Review by cportele — COMMENTED** [review]
In general this sounds fine as it is. Replace "PR" with "pull request".

We should discuss the "moderation team" and its email address. Maybe this should be just the SG, at least for now?

**Review by jonherrmann — CHANGES_REQUESTED** [review]
We have moved the governance documents to the "governance" repository. Please re-open this PR in the https://github.com/etf-validator/governance repository

**Comment by manmorjim** [comment]
@jonherrmann t's fin by us. We will re-open the PR in the governance repository

**Comment by manmorjim** [comment]
[PR](https://github.com/etf-validator/governance/pull/12) done.

**Pull request closed without merging**
